### ISSUE TITLE
Generate image is blank

### ISSUE THREAD

**Issue by mikenorgate** [yaqwsx/PcbDraw#91]
I'm attempting to generate an SVG for my PCB but the output image is blank, although when I look at the source of the SVG I can see there is data there

PcbDraw Version: 0.9.0
KiCad Version: 6.0.1

PCB Design

![image](https://user-images.githubusercontent.com/2479870/150813209-9eb43561-39f9-496d-b843-d3a56743725b.png)

Generated SVG

https://user-images.githubusercontent.com/2479870/150813349-f875ef92-cc77-4bfa-bf41-02a87780e651.svg

**Comment by Electro707** [comment]
Well this is what the SVG content looks like (opened with Inkscape, which I would recommend):
![image](https://user-images.githubusercontent.com/15680882/150824224-6dccdd68-7c48-48e7-af90-15223737ce10.png)

Still does no look fine as it's black. It looks like all `style` parameters in the svg data are empty, so possibly a bug. Try it with KiCAD 6 and see if colors show.

What are you using to view the SVG. For example on my system, my browser (Firefox) does not show any of the generated SVGs. I am guessing this is because of the huge internal scale KiCAD outputs it's SVGs in:
![image](https://user-images.githubusercontent.com/15680882/150824505-ee155f44-3277-46c8-8029-34cdca35361c.png)

**Comment by mikenorgate** [comment]
I was using Chrome as that's default on my system. I'll make sure to use Inkscape in the future

**Comment by Electro707** [comment]
Yeah, I do plan on hopefully getting that changed for KiCAD 7 so it could export svgs in a sane scale (https://gitlab.com/kicad/code/kicad/-/merge_requests/974).

**Comment by mikenorgate** [comment]
@yaqwsx it's available here https://github.com/mikenorgate/3d-printer-power-hat/tree/main/pcb

**Comment by yaqwsx** [comment]
@mikenorgate Could you upgrade to the upstream version of PcbDraw? With the upstream version I cannot reproduce the bug:

[Generated SVG](https://user-images.githubusercontent.com/1590880/156181318-cd55b753-3dfa-460e-a9db-1d1e0f3da4c1.svg)
![Screenshot from 2022-03-01 14-50-22](https://user-images.githubusercontent.com/1590880/156181444-3a9f0001-bd2e-4366-b750-bbf58e7c647f.png)

If it persists, what is you OS?

**Comment by mikenorgate** [comment]
@yaqwsx I updated to the upstream version and all works correctly, thanks

**Comment by yaqwsx** [comment]
Thanks, I will make a release then.
